import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import localFont from "next/font/local";
import { Footer } from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Shop.co",
  description: "Generated by create next app",
};
const SatoshiLights = localFont({
  src: "/fonts/Satoshi-Light.woff",
  display: "swap",
});
const SatoshiRegular = localFont({
  src: "/fonts/satoshi-regular.woff",
  display: "swap",
});

const SatoshiMedium = localFont({
  src: "/fonts/Satoshi-Medium.woff",
  display: "swap",
});

const SatoshiBold = localFont({
  src: "/fonts/Satoshi-Bold.woff",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SatoshiRegular.className} ${SatoshiLights.className} ${SatoshiBold.className}   ${SatoshiMedium.className} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
