import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Footer } from "@/components/Footer/Footer";
import { Urbanist } from "next/font/google";

export const metadata: Metadata = {
  title: "Shop.co",
  description: "Generated by create next app",
};

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"],
});

// const SatoshiLights = localFont({
//   src: "/fonts/Satoshi-Light.woff",
//   display: "swap",
// });

// const SatoshiMedium = localFont({
//   src: "/fonts/Satoshi-Medium.woff",
//   display: "swap",
// });

// const SatoshiBold = localFont({
//   src: "/fonts/Satoshi-Bold.woff",
//   display: "swap",
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${urbanist.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
